# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jiri Stepanek
description: My name is Jiri Stepanek and I’m 18 years old. Although I still haven't finished high school, I run a small agency called PalmMedia. I personally specialize in social media marketing and web development. I spent most of my time working for clients, in the GYM or just playing with my cat.
keywords: StyvekDrtic, Jiri Stepanek, Jirka, Juraj, webdev, social media, palmmedia, lanistae, arkun, gevo, Audiožurnál
author: palmmedia.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiristepanek.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
